### ISSUE TITLE
What are the labels for the initial concentration values?

### ISSUE THREAD

**Issue by tonyreina** [tamntnguyen/AAV-Triple-Transfection-Mechanistic-Model#1]
https://github.com/tamntnguyen/AAV-Triple-Transfection-Mechanistic-Model/blob/main/sim_full_params_mL.m#L22

I know they are all three 76,000. I believe the units are "plasmids/cell" (but maybe that's wrong). 

What are they measuring? Is it helper, rep/cap, goi? 

Thanks!
-Tony

**Comment by tamntnguyen** [comment]
Hi Tony,

Thanks for reaching out. The units are indeed "plasmids/cell". In our
experiment we used the same molar concentrations for all three plasmids.

-Tam

**Comment by tonyreina** [comment]
Tam,

Thanks for the confirmation. Is the order of the 3 variables: rep/cap,
helper, and GOI plasmids per cell?

Best.
Very Respectfully,
-Tony
